spring:
  application:
    name: GunilDa
  profiles:
    group:
      dev: dev
      prod: prod

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db
    username: dev
    password: devh2
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
  data:
    redis:
      host: localhost
      port: 6379

---
spring:
  config:
    activate:
      on-profile: prod
      #Mysql TO-DO
      #Redis TO-DO